# Generated by Django 5.0.2 on 2024-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../default_profile_qohjd5', upload_to='images/'),
        ),
    ]
